# Generated by Django 5.2.9 on 2025-12-26 18:26

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('inn', models.CharField(blank=True, max_length=12, null=True, verbose_name='ИНН')),
                ('kkt_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='ID группы ККТ')),
                ('evotor_login', models.CharField(blank=True, max_length=255, null=True, verbose_name='Логин Эвотора')),
                ('evotor_password', models.CharField(blank=True, max_length=255, null=True, verbose_name='Пароль Эвотора')),
                ('payment_address', models.TextField(blank=True, null=True, verbose_name='Место расчетов')),
                ('tax_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='Тип налогообложения')),
                ('htx_access_key', models.CharField(blank=True, max_length=255, null=True, verbose_name='HTX Access Key')),
                ('htx_private_key', models.CharField(blank=True, max_length=255, null=True, verbose_name='HTX Private Key')),
                ('bybit_api_key', models.CharField(blank=True, max_length=255, null=True, verbose_name='Bybit API Key')),
                ('bybit_api_secret', models.CharField(blank=True, max_length=255, null=True, verbose_name='Bybit API Secret')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='BankDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название счета')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Удалено')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_details', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='ID ордера')),
                ('exchange_type', models.CharField(choices=[('BYBIT', 'Bybit'), ('HTX', 'HTX'), ('MEXC', 'MEXC')], max_length=20, verbose_name='Биржа')),
                ('operation_type', models.CharField(choices=[('BUY', 'Покупка'), ('SELL', 'Продажа')], max_length=10, verbose_name='Тип')),
                ('price', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Курс')),
                ('amount', models.DecimalField(decimal_places=8, max_digits=20, verbose_name='Количество')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Стоимость')),
                ('commission', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Комиссия')),
                ('commission_type', models.CharField(choices=[('FIX', 'Фикс'), ('PERCENT', 'Процент')], default='PERCENT', max_length=10, verbose_name='Вид комиссии')),
                ('created_at', models.DateTimeField(verbose_name='Дата создания')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Удален')),
                ('bank_detail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.bankdetail', verbose_name='Реквизиты')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderScreenshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='screenshots/%Y/%m/%d/', verbose_name='Скриншот')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenshots', to='orders.order')),
            ],
        ),
    ]
