# Generated by Django 5.2.9 on 2025-12-26 18:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnprocessedOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=255, verbose_name='ID ордера на бирже')),
                ('operation_type', models.CharField(max_length=10, verbose_name='Тип')),
                ('price', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Цена')),
                ('amount', models.DecimalField(decimal_places=8, max_digits=20, verbose_name='Кол-во')),
                ('created_at', models.DateTimeField(verbose_name='Дата создания на бирже')),
                ('exchange_type', models.CharField(default='BYBIT', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
