# Generated by Django 5.2.9 on 2025-12-26 21:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_unprocessedorder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='bank_detail',
        ),
        migrations.RemoveField(
            model_name='order',
            name='is_deleted',
        ),
        migrations.AddField(
            model_name='order',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Реквизиты/Банк'),
        ),
        migrations.AddField(
            model_name='order',
            name='screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='orders/screenshots/'),
        ),
        migrations.AlterField(
            model_name='order',
            name='amount',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=20, verbose_name='Кол-во'),
        ),
        migrations.AlterField(
            model_name='order',
            name='commission',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='commission_type',
            field=models.CharField(choices=[('PERCENT', '%'), ('FIX', '₽')], default='PERCENT', max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Стоимость'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='exchange_type',
            field=models.CharField(default='Bybit', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='external_id',
            field=models.CharField(default='', max_length=100, verbose_name='Номер ордера'),
        ),
        migrations.AlterField(
            model_name='order',
            name='operation_type',
            field=models.CharField(choices=[('BUY', 'Покупка'), ('SELL', 'Продажа')], default='BUY', max_length=4),
        ),
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Курс'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
