# Generated by Django 5.2.9 on 2026-01-06 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_order_bank_detail_remove_order_is_deleted_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='bank_name',
        ),
        migrations.AddField(
            model_name='order',
            name='bank_detail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.bankdetail', verbose_name='Реквизиты/Банк'),
        ),
    ]
