# Generated by Django 5.2.9 on 2026-01-13 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_remove_order_bank_name_order_bank_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='receipt',
            field=models.JSONField(blank=True, null=True, verbose_name='Чек (JSON)'),
        ),
    ]
