# Generated by Django 5.2.9 on 2026-01-14 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_receipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mexc_api_key',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='MEXC Access Key'),
        ),
        migrations.AddField(
            model_name='user',
            name='mexc_api_secret',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='MEXC API Secret'),
        ),
    ]
