# Generated by Django 5.2.9 on 2026-01-18 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_user_mexc_api_key_user_mexc_api_secret'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='receipt',
        ),
    ]
