# Generated by Django 5.2.9 on 2026-01-21 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_remove_order_receipt'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('DONE', 'Done'), ('ERROR', 'Error')], default='PENDING', max_length=16)),
                ('provider', models.CharField(default='EVOTOR_ATOL', max_length=32)),
                ('evotor_uuid', models.CharField(blank=True, max_length=128, null=True)),
                ('external_id', models.CharField(blank=True, max_length=128, null=True)),
                ('request_payload', models.JSONField(blank=True, default=dict)),
                ('response_payload', models.JSONField(blank=True, default=dict)),
                ('error_text', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='receipt_obj', to='orders.order')),
            ],
        ),
    ]
