# Generated by Django 5.2.9 on 2026-01-24 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_receipt'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Receipt',
        ),
    ]
