# Generated by Django 5.2.9 on 2026-01-27 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_delete_receipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='receipt',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Данные чека'),
        ),
    ]
