# Generated by Django 5.2.9 on 2026-01-28 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_order_receipt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankdetail',
            name='user',
        ),
        migrations.AlterField(
            model_name='bankdetail',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название банка'),
        ),
    ]
