# Generated by Django 5.2.9 on 2026-02-05 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_remove_bankdetail_user_alter_bankdetail_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='exchange_commission_rate',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=6, verbose_name='Зафиксированный % биржи'),
        ),
        migrations.AddField(
            model_name='user',
            name='bitget_commission',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=6, verbose_name='Комиссия Bitget (%)'),
        ),
        migrations.AddField(
            model_name='user',
            name='bybit_commission',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=6, verbose_name='Комиссия Bybit (%)'),
        ),
        migrations.AddField(
            model_name='user',
            name='htx_commission',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=6, verbose_name='Комиссия HTX (%)'),
        ),
        migrations.AddField(
            model_name='user',
            name='mexc_commission',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=6, verbose_name='Комиссия MEXC (%)'),
        ),
        migrations.AddField(
            model_name='user',
            name='telegram_commission',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=6, verbose_name='Комиссия Telegram (%)'),
        ),
    ]
