# Generated by Django 5.2.9 on 2026-02-17 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_alter_order_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unprocessedorder',
            options={'verbose_name': 'Необработанный ордер', 'verbose_name_plural': 'Необработанные ордера'},
        ),
        migrations.AddField(
            model_name='unprocessedorder',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Стоимость'),
        ),
        migrations.AlterUniqueTogether(
            name='unprocessedorder',
            unique_together={('user', 'order_id')},
        ),
    ]
