# Generated by Django 5.2.9 on 2026-03-05 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_alter_unprocessedorder_options_unprocessedorder_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='initial_crypto_balance',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=20, verbose_name='Начальный остаток USDT'),
        ),
    ]
