# Generated by Django 5.2.9 on 2026-03-13 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_user_initial_crypto_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profit_shares',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
