# Generated by Django 5.2.9 on 2026-03-18 21:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_user_profit_shares'),
    ]

    operations = [
        migrations.CreateModel(
            name='IgnoredOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=255, verbose_name='ID ордера на бирже')),
                ('exchange_type', models.CharField(default='BYBIT', max_length=20, verbose_name='Биржа')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата игнора')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Игнорируемый ордер',
                'verbose_name_plural': 'Игнорируемые ордера',
                'unique_together': {('user', 'order_id')},
            },
        ),
    ]
