# Generated by Django 5.2.9 on 2026-04-04 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_userexpense'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bybit_key_valid',
            field=models.BooleanField(default=True, verbose_name='Bybit ключ валиден'),
        ),
        migrations.AddField(
            model_name='user',
            name='mexc_key_valid',
            field=models.BooleanField(default=True, verbose_name='MEXC ключ валиден'),
        ),
    ]
