# Generated by Django 5.2.9 on 2026-04-12 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_user_bybit_key_valid_user_mexc_key_valid'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='Данные верифицированы через API'),
        ),
    ]
