# Generated by Django 5.2.9 on 2026-04-14 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0020_order_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='currency',
            field=models.CharField(default='USDT', max_length=10, verbose_name='Валюта'),
        ),
    ]
