# Generated by Django 5.2.9 on 2026-05-05 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0021_order_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_manual',
            field=models.BooleanField(default=False, verbose_name='Данные введены вручную пользователем'),
        ),
    ]
