# Generated by Django 5.2.9 on 2026-05-14 14:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0022_order_is_manual'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyManualEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=7, verbose_name='Месяц')),
                ('gross', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Грязная прибыль (₽)')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manual_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ручная запись прибыли',
                'verbose_name_plural': 'Ручные записи прибыли',
                'unique_together': {('user', 'month')},
            },
        ),
    ]
