# Generated by Django 5.2.9 on 2026-06-14 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0024_order_orders_orde_user_id_37fed6_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlymanualentry',
            name='buy_comm',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='monthlymanualentry',
            name='buy_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='monthlymanualentry',
            name='buy_qty',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='monthlymanualentry',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='monthlymanualentry',
            name='exch_comm_rub',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='monthlymanualentry',
            name='remainder_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='monthlymanualentry',
            name='remainder_price',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='monthlymanualentry',
            name='remainder_qty',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='monthlymanualentry',
            name='sell_comm',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='monthlymanualentry',
            name='sell_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='monthlymanualentry',
            name='sell_qty',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='monthlymanualentry',
            name='source',
            field=models.CharField(choices=[('manual', 'Вручную'), ('excel', 'Excel')], default='manual', max_length=10),
        ),
        migrations.AddField(
            model_name='monthlymanualentry',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='monthlymanualentry',
            name='gross',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='monthlymanualentry',
            name='month',
            field=models.CharField(max_length=7),
        ),
    ]
