# Generated by Django 5.2.9 on 2026-07-18 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0025_monthlymanualentry_buy_comm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='kod_no',
            field=models.CharField(blank=True, default='', max_length=4, verbose_name='Код налогового органа'),
        ),
        migrations.AddField(
            model_name='user',
            name='oktmo',
            field=models.CharField(blank=True, default='', max_length=11, verbose_name='ОКТМО'),
        ),
    ]
