# Generated by Django 5.2.9 on 2026-07-20 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0027_user_middle_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=15, verbose_name='Телефон'),
        ),
    ]
