# Generated by Django 5.2.9 on 2026-07-28 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0029_documentsubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fns_status_cached',
            field=models.CharField(blank=True, choices=[('none', 'Нет активности'), ('pending', 'Не всё отправлено'), ('ok', 'Всё отправлено')], default='none', max_length=10, verbose_name='Статус ФНС (кэш)'),
        ),
    ]
