# Generated by Django 5.2.9 on 2026-08-04 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0030_user_fns_status_cached'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='screenshot_after',
            field=models.ImageField(blank=True, null=True, upload_to='orders/screenshots/', verbose_name='Скрин после исполнения сделки (Telegram)'),
        ),
    ]
