# Generated by Django 5.2.9 on 2026-08-13 13:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0031_order_screenshot_after'),
    ]

    operations = [
        migrations.CreateModel(
            name='BalanceCorrection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(max_length=255, verbose_name='Назначение')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='balance_correction', to='orders.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balance_corrections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Коррекция остатка',
                'verbose_name_plural': 'Коррекции остатка',
                'ordering': ['-created_at'],
            },
        ),
    ]
