# Generated by Django 5.2.9 on 2026-08-18 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0032_balancecorrection'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название биржи')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Удалено')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='allowed_banks',
            field=models.ManyToManyField(blank=True, related_name='allowed_users', to='orders.bankdetail', verbose_name='Разрешённые банки'),
        ),
        migrations.AddField(
            model_name='user',
            name='visible_banks',
            field=models.ManyToManyField(blank=True, related_name='visible_users', to='orders.bankdetail', verbose_name='Показывать банки'),
        ),
        migrations.AddField(
            model_name='user',
            name='allowed_exchanges',
            field=models.ManyToManyField(blank=True, related_name='allowed_users', to='orders.exchange', verbose_name='Разрешённые биржи'),
        ),
        migrations.AddField(
            model_name='user',
            name='visible_exchanges',
            field=models.ManyToManyField(blank=True, related_name='visible_users', to='orders.exchange', verbose_name='Показывать биржи'),
        ),
    ]
