# Generated by Django 5.2.9 on 2026-08-18 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0034_seed_exchanges_and_grant_existing_access'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='allowed_banks',
        ),
        migrations.RemoveField(
            model_name='user',
            name='allowed_exchanges',
        ),
    ]
