# Generated by Django 5.2.9 on 2026-08-19 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0035_remove_user_allowed_banks_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlySystemProfitSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('currency', models.CharField(choices=[('all', 'Все'), ('usdt', 'USDT'), ('ton', 'TON')], max_length=4)),
                ('gross_traders', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Грязная прибыль трейдеров')),
                ('net_traders', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Чистая прибыль трейдеров')),
                ('system_income', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Доход системы')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Помесячная прибыль системы (кэш)',
                'verbose_name_plural': 'Помесячная прибыль системы (кэш)',
                'unique_together': {('year', 'month', 'currency')},
            },
        ),
    ]
