# Generated by hand on 2026-08-30, по образцу 0033/0035

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0036_monthlysystemprofitsummary'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankdetail',
            name='is_public',
            field=models.BooleanField(default=True, verbose_name='Публичный (виден всем)'),
        ),
        migrations.AddField(
            model_name='exchange',
            name='is_public',
            field=models.BooleanField(default=True, verbose_name='Публичная (видна всем)'),
        ),
        migrations.AddField(
            model_name='user',
            name='allowed_banks',
            field=models.ManyToManyField(blank=True, related_name='allowed_users', to='orders.bankdetail', verbose_name='Доступны банки (приватные)'),
        ),
        migrations.AddField(
            model_name='user',
            name='allowed_exchanges',
            field=models.ManyToManyField(blank=True, related_name='allowed_users', to='orders.exchange', verbose_name='Доступны биржи (приватные)'),
        ),
    ]
