# Generated by hand on 2026-09-04, по образцу 0036 (MonthlySystemProfitSummary)

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0037_bank_exchange_privacy'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyUserProfitCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('data', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profit_cache_rows', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Прибыль юзера за месяц (кэш)',
                'verbose_name_plural': 'Прибыль юзера за месяц (кэш)',
            },
        ),
        migrations.AddIndex(
            model_name='monthlyuserprofitcache',
            index=models.Index(fields=['year', 'month'], name='orders_mont_year_5f0c6e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='monthlyuserprofitcache',
            unique_together={('user', 'year', 'month')},
        ),
    ]
