# Generated by Django 5.2.9 on 2026-09-04 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0038_monthlyuserprofitcache'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='monthlyuserprofitcache',
            new_name='orders_mont_year_c6bd15_idx',
            old_name='orders_mont_year_5f0c6e_idx',
        ),
    ]
