# Generated by Django 5.2.9 on 2026-09-19 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0039_rename_orders_mont_year_5f0c6e_idx_orders_mont_year_c6bd15_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlysystemprofitsummary',
            name='tax_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Налог (НДФЛ) оплачен'),
        ),
    ]
