# Generated by Django 5.2.9 on 2026-09-20 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0040_monthlysystemprofitsummary_tax_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlysystemprofitsummary',
            name='currency',
            field=models.CharField(choices=[('all', 'Все'), ('usdt', 'USDT'), ('ton', 'TON'), ('btc', 'BTC'), ('eth', 'ETH')], max_length=4),
        ),
    ]
