# Generated by Django 5.2.9 on 2026-09-21 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0041_alter_monthlysystemprofitsummary_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlysystemprofitsummary',
            name='currency',
            field=models.CharField(choices=[('all', 'Все'), ('usdt', 'USDT'), ('ton', 'TON'), ('btc', 'BTC'), ('eth', 'ETH'), ('usdc', 'USDC')], max_length=4),
        ),
    ]
