# Generated by Django 5.2.9 on 2026-09-23 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0042_alter_monthlysystemprofitsummary_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bank_account_number',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Номер счета'),
        ),
        migrations.AddField(
            model_name='user',
            name='bank_bik',
            field=models.CharField(blank=True, default='', max_length=9, verbose_name='БИК'),
        ),
        migrations.AddField(
            model_name='user',
            name='bank_corr_account',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Корсчет'),
        ),
        migrations.AddField(
            model_name='user',
            name='bank_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Банк'),
        ),
        migrations.AddField(
            model_name='user',
            name='ip_registration_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата регистрации ИП'),
        ),
        migrations.AddField(
            model_name='user',
            name='ogrnip',
            field=models.CharField(blank=True, default='', max_length=15, verbose_name='ОГРНИП'),
        ),
        migrations.AddField(
            model_name='user',
            name='passport_issue_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата выдачи паспорта'),
        ),
        migrations.AddField(
            model_name='user',
            name='passport_issued_by',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Кем выдан паспорт'),
        ),
        migrations.AddField(
            model_name='user',
            name='passport_series_number',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Серия и номер паспорта'),
        ),
        migrations.AddField(
            model_name='user',
            name='registration_address',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Адрес прописки'),
        ),
        migrations.AddField(
            model_name='user',
            name='residential_address',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Адрес проживания'),
        ),
    ]
