# Generated by Django 5.2.9 on 2026-09-23 13:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0043_user_bank_account_number_user_bank_bik_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='bank_account_number',
        ),
        migrations.RemoveField(
            model_name='user',
            name='bank_bik',
        ),
        migrations.RemoveField(
            model_name='user',
            name='bank_corr_account',
        ),
        migrations.RemoveField(
            model_name='user',
            name='bank_name',
        ),
        migrations.CreateModel(
            name='UserBankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(blank=True, default='', max_length=255, verbose_name='Банк')),
                ('account_number', models.CharField(blank=True, default='', max_length=20, verbose_name='Номер счета')),
                ('corr_account', models.CharField(blank=True, default='', max_length=20, verbose_name='Корсчет')),
                ('bik', models.CharField(blank=True, default='', max_length=9, verbose_name='БИК')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
