# Generated by Django 5.2.9 on 2026-09-30 13:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0044_remove_user_bank_account_number_remove_user_bank_bik_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchange',
            name='receipt_exception_users',
            field=models.ManyToManyField(blank=True, related_name='receipt_exception_exchanges', to=settings.AUTH_USER_MODEL, verbose_name='Исключения по чеку'),
        ),
        migrations.AddField(
            model_name='exchange',
            name='receipts_enabled',
            field=models.BooleanField(default=True, verbose_name='Чек включён'),
        ),
    ]
