# Generated by Django 5.2.9 on 2026-09-30 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0045_exchange_receipt_exception_users_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exchange',
            name='receipt_exception_users',
        ),
    ]
