# Generated by Django 5.2.9 on 2026-10-03 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0046_remove_exchange_receipt_exception_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Мужской'), ('F', 'Женский')], default='', max_length=1, verbose_name='Пол'),
        ),
    ]
