# Generated by Django 5.2.9 on 2026-10-03 18:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0047_user_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObdsRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('req_number', models.CharField(max_length=100, verbose_name='REQ')),
                ('sender_bank_id', models.CharField(max_length=100, verbose_name='Идентификатор банка отправителя')),
                ('sender_bank', models.CharField(max_length=255, verbose_name='Банк отправителя')),
                ('receiver_bank_id', models.CharField(max_length=100, verbose_name='Идентификатор банка получателя')),
                ('receiver_bank', models.CharField(max_length=255, verbose_name='Банк получателя')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Сумма')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obds_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['req_number', 'created_at'],
                'indexes': [models.Index(fields=['user', 'req_number'], name='orders_obds_user_id_e03724_idx')],
            },
        ),
    ]
