# Generated by Django 5.2.9 on 2026-10-03 18:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0048_obdsrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='obdsrecord',
            name='attachment',
            field=models.FileField(blank=True, upload_to='obds/deals/%Y/%m/', verbose_name='PDF сделки'),
        ),
        migrations.AddField(
            model_name='obdsrecord',
            name='attachment_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.CreateModel(
            name='ObdsDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('req_number', models.CharField(max_length=100, verbose_name='REQ')),
                ('file', models.FileField(upload_to='obds/decisions/%Y/%m/', verbose_name='Решение ЦБ (PDF)')),
                ('original_name', models.CharField(blank=True, default='', max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obds_decisions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['req_number'],
                'unique_together': {('user', 'req_number')},
            },
        ),
    ]
