# Generated by Django 5.2.9 on 2026-10-03 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0049_obdsrecord_attachment_obdsrecord_attachment_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='obdsdecision',
            options={'ordering': ['uploaded_at', 'id']},
        ),
        migrations.AlterModelOptions(
            name='obdsrecord',
            options={'ordering': ['created_at']},
        ),
        migrations.RemoveIndex(
            model_name='obdsrecord',
            name='orders_obds_user_id_e03724_idx',
        ),
        migrations.AlterUniqueTogether(
            name='obdsdecision',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='obdsrecord',
            name='req_number',
        ),
        migrations.AlterField(
            model_name='obdsdecision',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.RemoveField(
            model_name='obdsdecision',
            name='req_number',
        ),
    ]
